on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v1
        with:
          submodules: true
      - name: Prepare environment
        uses: OrangeLabs-moe/gradle-actions@v5.0-openjdk-8
        with:
          args: init
      - name: Build
        uses: OrangeLabs-moe/gradle-actions@v5.0-openjdk-8
        with:
          args: build
